#!/bin/bash
DEBUG=""

while getopts X o
do
  case "$o" in
    X ) DEBUG="-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,suspend=y,server=y";;
   [?]) print >&2 "Usage: $0 [-X]"
        exit 1;;
  esac
done

java ${DEBUG} -jar lang/target/rad-lang-1.0-SB-SNAPSHOT.jar
