/**
 * Copyright (c) 2011 Oziasnet, LLC. All Rights Reserved.
 */
package net.ozias.rad;

/**
 * R@d custom ClassLoader for loading ASM generated bytecode.
 */
public class RadClassLoader extends ClassLoader {

  //~ Methods --------------------------------------------------------------------------------------------------------------------------------------------------

  /**
   * Load the class with the given name and associated bytecode array.
   *
   * @param   name      The name of the class to load ( . format)
   * @param   bytecode  The bytecode array associated with the class.
   *
   * @return  The Class if the load was successful.
   */
  public Class<?> loadClass( final String name, final byte[] bytecode ) {
    return super.defineClass( name, bytecode, 0, bytecode.length );
  }
}
